"""Preset scenarios for the "Try your own event" form.

Each numeric field is (default, low, high). The default fills the form;
low/high are the sensible range for a "randomise" button or slider limits.
neighbours_pct is the 24 h change at the three neighbouring gauges, in the
order the form shows them.

source = "real"         -> numbers taken from the September 2026 data
source = "illustrative" -> plausible numbers, not measured
"""

SCENARIOS = [
    {
        "name": "Sensor dropout (Bow at Calgary)",
        "expect": "Sensor fault -> quarantine + ticket, no phone call",
        "source": "real",
        "gauge": "05BH004", "measure": "flow", "spotted_as": "auto",
        "reading_now": (0.0, 0.0, 0.5),
        "reading_6h_ago": (70.7, 60.0, 80.0),
        "rain_24h_mm": (0.0, 0.0, 2.0),
        "rain_48h_mm": (0.0, 0.0, 5.0),
        "minutes_no_data": (0, 0, 0),
        "identical_readings": (0, 0, 2),
        "rain_gauge_trust": (1.0, 0.8, 1.0),
        "single_reading_jump": False,
        "neighbours_pct": [(1, -3, 3), (6, -8, 8), (-2, -5, 5)],
    },
    {
        "name": "One-reading spike (Bow at Banff)",
        "expect": "Sensor fault -> quarantine + ticket, no phone call",
        "source": "real",
        "gauge": "05BB001", "measure": "flow", "spotted_as": "auto",
        "reading_now": (63.3, 58.0, 80.0),
        "reading_6h_ago": (40.5, 38.0, 43.0),
        "rain_24h_mm": (0.0, 0.0, 2.0),
        "rain_48h_mm": (0.0, 0.0, 5.0),
        "minutes_no_data": (0, 0, 0),
        "identical_readings": (0, 0, 2),
        "rain_gauge_trust": (1.0, 0.8, 1.0),
        "single_reading_jump": True,
        "neighbours_pct": [(0, -3, 3), (0, -3, 3), (0, -3, 3)],
    },
    {
        "name": "Gauge goes silent (Bow near Cochrane)",
        "expect": "Sensor fault -> ticket only, no phone call",
        "source": "real",
        "gauge": "05BH005", "measure": "flow", "spotted_as": "auto",
        "reading_now": (69.0, 60.0, 75.0),
        "reading_6h_ago": (69.0, 60.0, 75.0),
        "rain_24h_mm": (0.0, 0.0, 2.0),
        "rain_48h_mm": (0.0, 0.0, 5.0),
        "minutes_no_data": (185, 60, 360),
        "identical_readings": (0, 0, 2),
        "rain_gauge_trust": (1.0, 0.8, 1.0),
        "single_reading_jump": False,
        "neighbours_pct": [(0, -3, 3), (1, -3, 3), (0, -3, 3)],
    },
    {
        "name": "Dam release (Elbow below Glenmore Dam)",
        "expect": "Operational change -> logged, no phone call",
        "source": "real",
        "gauge": "05BJ001", "measure": "flow", "spotted_as": "auto",
        "reading_now": (4.96, 4.0, 5.5),
        "reading_6h_ago": (1.53, 1.4, 2.8),
        "rain_24h_mm": (0.0, 0.0, 2.0),
        "rain_48h_mm": (0.0, 0.0, 5.0),
        "minutes_no_data": (0, 0, 0),
        "identical_readings": (0, 0, 2),
        "rain_gauge_trust": (1.0, 0.8, 1.0),
        "single_reading_jump": False,
        "neighbours_pct": [(1, -2, 2), (0, -3, 3), (0, -3, 3)],
    },
    {
        "name": "Flood starting (Indian Brook)",
        "expect": "Natural event -> phone call",
        "source": "illustrative",  # neighbour changes are real; reading_now is a plausible early value
        "gauge": "01FE002", "measure": "flow", "spotted_as": "auto",
        "reading_now": (4.0, 2.0, 15.0),
        "reading_6h_ago": (0.72, 0.6, 0.9),
        "rain_24h_mm": (20.0, 10.0, 40.0),
        "rain_48h_mm": (22.0, 10.0, 50.0),
        "minutes_no_data": (0, 0, 0),
        "identical_readings": (0, 0, 2),
        "rain_gauge_trust": (1.0, 0.8, 1.0),
        "single_reading_jump": False,
        "neighbours_pct": [(18, 10, 40), (34, 20, 60), (36, 20, 60)],
    },
    {
        "name": "Flood above the historical limit (River Denys)",
        "expect": "Natural event, NOT a sensor fault -> phone call, nothing quarantined",
        "source": "illustrative",  # 59.8 peak and 44.4 limit are real; the rest is plausible
        "gauge": "01FG001", "measure": "flow", "spotted_as": "auto",
        "reading_now": (59.8, 45.0, 80.0),
        "reading_6h_ago": (15.0, 5.0, 25.0),
        "rain_24h_mm": (110.0, 60.0, 180.0),
        "rain_48h_mm": (125.0, 70.0, 250.0),
        "minutes_no_data": (0, 0, 0),
        "identical_readings": (0, 0, 2),
        "rain_gauge_trust": (1.0, 0.8, 1.0),
        "single_reading_jump": False,
        "neighbours_pct": [(150, 60, 400), (200, 60, 500), (120, 60, 400)],
    },
    {
        "name": "Broken rain gauge (Elbow at Bragg Creek)",
        "expect": "Sensor fault -> the impossible rain figure is ignored",
        "source": "real",  # dip is real; 608 mm/h is the stuck Springbank gauge
        "gauge": "05BJ004", "measure": "flow", "spotted_as": "auto",
        "reading_now": (2.26, 1.5, 3.5),
        "reading_6h_ago": (6.8, 6.0, 7.5),
        "rain_24h_mm": (608.0, 300.0, 700.0),
        "rain_48h_mm": (608.0, 300.0, 1400.0),
        "minutes_no_data": (0, 0, 0),
        "identical_readings": (0, 0, 2),
        "rain_gauge_trust": (0.0, 0.0, 0.2),
        "single_reading_jump": True,
        "neighbours_pct": [(0, -3, 3), (0, -3, 3), (0, -3, 3)],
    },
    {
        "name": "Unclear rise (Jumpingpound Creek)",
        "expect": "Inconclusive -> shows what the system does when it is not sure",
        "source": "illustrative",
        "gauge": "05BH015", "measure": "flow", "spotted_as": "auto",
        "reading_now": (3.0, 2.4, 4.0),
        "reading_6h_ago": (1.5, 1.2, 1.8),
        "rain_24h_mm": (0.0, 0.0, 3.0),
        "rain_48h_mm": (2.0, 0.0, 6.0),
        "minutes_no_data": (0, 0, 0),
        "identical_readings": (0, 0, 2),
        "rain_gauge_trust": (1.0, 0.8, 1.0),
        "single_reading_jump": False,
        "neighbours_pct": [(3, -5, 8), (0, -5, 5), (2, -5, 8)],
    },
]
